[project]
name = "git-hooks"
version = "0.3.0"
description = "一个不起眼的钩子"
readme = "README.md"
# requires-python = ">=3.13"
dependencies = []

[tool.commitizen]
name = "cz_gitmoji"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "pep621"
major_version_zero = true
